# .github/workflows/frontend-ci-wp.yml
#
# ============================================
# CONFIGURATION - Update this URL before use:
# ============================================
# YOUR_SITE_URL: http://72.62.125.163:8002/
# ============================================

name: WordPress Quality Checks

env:
  YOUR_SITE_URL: "http://72.62.125.163:8002/"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # === PILLAR 2: Code Validation (Runs on every Pull Request) ===
  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Best practice to use latest major version
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, json
          coverage: none
          # Caching composer dependencies for faster runs
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run WordPress Coding Standards check
        run: vendor/bin/phpcs --standard=WordPress wp-content/

  frontend-lint-and-audit:
    name: Frontend Lint & Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Caching npm packages for faster runs
      - name: Install npm dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint wp-content/ --ext .js,.jsx --no-error-on-unmatched-pattern || true
      - name: Check formatting with Prettier
        run: npx prettier --check "wp-content/**/*.{js,css,scss}" --ignore-unknown || true
      - name: Audit for npm security vulnerabilities
        run: npm audit --audit-level=high || true

  # === PILLAR 3: Live Site Audit (Runs only after merging to main) ===
  live-audit:
    name: Live URL Audit
    needs: [php-lint, frontend-lint-and-audit]
    # This 'if' condition ensures this job only runs on pushes to the 'main' branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run Lighthouse and Generate Report
        run: |
          npm install -g lighthouse
          lighthouse ${{ env.YOUR_SITE_URL }} --output=json --output=html --output-path=./lighthouse-report --chrome-flags="--headless --no-sandbox"
          echo "Lighthouse files generated:"
          ls -la lighthouse-report*
      - name: Generate Markdown Report
        run: |
          node << 'SCRIPT'
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('./lighthouse-report.report.json', 'utf8'));
          const perf = Math.round(data.categories.performance.score * 100);
          const a11y = Math.round(data.categories.accessibility.score * 100);
          const bp = Math.round(data.categories['best-practices'].score * 100);
          const seo = Math.round(data.categories.seo.score * 100);
          const fcp = data.audits['first-contentful-paint'].displayValue;
          const lcp = data.audits['largest-contentful-paint'].displayValue;
          const tbt = data.audits['total-blocking-time'].displayValue;
          const cls = data.audits['cumulative-layout-shift'].displayValue;
          const si = data.audits['speed-index'].displayValue;
          const report = `# Lighthouse Report

          **URL:** ${data.finalUrl}
          **Generated:** ${new Date(data.fetchTime).toLocaleString()}
          **Lighthouse Version:** ${data.lighthouseVersion}

          ## Scores

          | Category | Score |
          |----------|-------|
          | Performance | ${perf}% |
          | Accessibility | ${a11y}% |
          | Best Practices | ${bp}% |
          | SEO | ${seo}% |

          ## Performance Metrics

          | Metric | Value |
          |--------|-------|
          | First Contentful Paint | ${fcp} |
          | Largest Contentful Paint | ${lcp} |
          | Total Blocking Time | ${tbt} |
          | Cumulative Layout Shift | ${cls} |
          | Speed Index | ${si} |

          ## Summary

          This report was automatically generated by the WordPress Quality Checks workflow.
          `.split('\n').map(line => line.trim()).join('\n');
          fs.writeFileSync('./Lighthouse-Report.md', report);
          console.log('Markdown report generated');
          SCRIPT
          cat Lighthouse-Report.md
      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lighthouse-report.report.html
            lighthouse-report.report.json
            Lighthouse-Report.md
      - name: Setup Ruby for WPScan
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install and Run WPScan
        run: |
          gem install wpscan
          wpscan --url ${{ env.YOUR_SITE_URL }} --api-token ${{ secrets.WPSCAN_API_TOKEN }} --format cli || true
        continue-on-error: true